# Generated by Django 4.0.1 on 2022-01-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0006_genre_remove_movie_genres_movie_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quality',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watch',
            field=models.URLField(blank=True, null=True),
        ),
    ]
